# Generated by Django 3.1.3 on 2020-11-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
