# Generated by Django 3.1.3 on 2020-11-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_address',
            old_name='comments',
            new_name='directions',
        ),
    ]
