# Generated by Django 3.1.3 on 2020-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201122_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductTag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(to='cms.ProductTag'),
        ),
    ]
