# Generated by Django 3.1.3 on 2020-11-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201122_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='Product_Tag',
        ),
    ]
