# Generated by Django 3.1.3 on 2020-11-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201120_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='surname',
        ),
    ]
