# Generated by Django 3.1.3 on 2020-11-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201122_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='directions',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
